name: Build Patcher

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '9.0.103'

jobs:
  build-linux-x64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: |
        cd WiiLink-Patcher-CLI
        dotnet publish -c Release -r "linux-x64" /p:AssemblyName="WiiLinkPatcher_Linux-x64_${{ github.sha }}"
    
    - name: Tar Build
      run: |
        tar cvf WiiLinkPatcher_Linux-x64_${{ github.sha }}.tar --directory=WiiLink-Patcher-CLI/bin/Release/net9.0-windows10.0.22621.0/linux-x64/native/ WiiLinkPatcher_Linux-x64_${{ github.sha }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        path: WiiLinkPatcher_Linux-x64_${{ github.sha }}.tar
        name: WiiLinkPatcher_Linux-x64_${{ github.sha }}

  build-linux-arm64:

    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: |
        cd WiiLink-Patcher-CLI
        dotnet publish -c Release -r "linux-arm64" /p:AssemblyName="WiiLinkPatcher_Linux-arm64_${{ github.sha }}"
    
    - name: Tar Build
      run: |
        tar cvf WiiLinkPatcher_Linux-arm64_${{ github.sha }}.tar --directory=WiiLink-Patcher-CLI/bin/Release/net9.0-windows10.0.22621.0/linux-arm64/native/ WiiLinkPatcher_Linux-arm64_${{ github.sha }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        path: WiiLinkPatcher_Linux-arm64_${{ github.sha }}.tar
        name: WiiLinkPatcher_Linux-arm64_${{ github.sha }}

  build-windows-x64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: |
        cd WiiLink-Patcher-CLI
        dotnet publish -c Release -r "win-x64" /p:AssemblyName="WiiLinkPatcher_Windows-x64_${{ github.sha }}"

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        path: D:\a\WiiLink24-Patcher\WiiLink24-Patcher\WiiLink-Patcher-CLI\bin\Release\net9.0-windows10.0.22621.0\win-x64\publish\WiiLinkPatcher_Windows-x64_${{ github.sha }}.exe
        name: WiiLinkPatcher_Windows-x64_${{ github.sha }}
  
  build-windows-arm64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: |
        cd WiiLink-Patcher-CLI
        dotnet publish -c Release -r "win-arm64" /p:AssemblyName="WiiLinkPatcher_Windows-arm64_${{ github.sha }}"

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        path: D:\a\WiiLink24-Patcher\WiiLink24-Patcher\WiiLink-Patcher-CLI\bin\Release\net9.0-windows10.0.22621.0\win-arm64\publish\WiiLinkPatcher_Windows-arm64_${{ github.sha }}.exe
        name: WiiLinkPatcher_Windows-arm64_${{ github.sha }}

  build-macos-x64:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: |
        cd WiiLink-Patcher-CLI
        dotnet publish -c Release -r "osx-x64" /p:AssemblyName="WiiLinkPatcher_macOS-x64_${{ github.sha }}"

    - name: Tar Build
      run: |
        tar cvf WiiLinkPatcher_macOS-x64_${{ github.sha }}.tar --directory=WiiLink-Patcher-CLI/bin/Release/net9.0-windows10.0.22621.0/osx-x64/native/ WiiLinkPatcher_macOS-x64_${{ github.sha }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        path: WiiLinkPatcher_macOS-x64_${{ github.sha }}.tar
        name: WiiLinkPatcher_macOS-x64_${{ github.sha }}
  
  build-macos-arm64:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: |
        cd WiiLink-Patcher-CLI
        dotnet publish -c Release -r "osx-arm64" /p:AssemblyName="WiiLinkPatcher_macOS-arm64_${{ github.sha }}"

    - name: Tar Build
      run: |
        tar cvf WiiLinkPatcher_macOS-arm64_${{ github.sha }}.tar --directory=WiiLink-Patcher-CLI/bin/Release/net9.0-windows10.0.22621.0/osx-arm64/native/ WiiLinkPatcher_macOS-arm64_${{ github.sha }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        path: WiiLinkPatcher_macOS-arm64_${{ github.sha }}.tar
        name: WiiLinkPatcher_macOS-arm64_${{ github.sha }}

